apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ekbxcvpr
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ekbxcvpr:18779e8468a4e3e79abaf642d5b1145b06e6d79a@sha256:a8694ceeae62e7c45b6174d98c7c295b09f0b60086363f45f4abe5be08745b1a
          name: container-image
